import fs from 'fs'
import path from 'path'
import type { OutputRenderer } from './base.js'
import type { Report } from '../types.js'

export class MarkdownRenderer implements OutputRenderer {
  readonly format = 'markdown'

  async render(report: Report, outDir: string): Promise<string> {
    fs.mkdirSync(outDir, { recursive: true })

    const lines: string[] = [
      `# ${report.title}`,
      ``,
      `> Generated by adrcli on ${report.generatedAt.toISOString()}`,
      ``,
      `---`,
      ``,
      `## Problem Statement`,
      ``,
      `**${report.problem.title}**`,
      ``,
      report.problem.description,
      ``,
    ]

    if (report.problem.constraints && Object.keys(report.problem.constraints).length > 0) {
      lines.push(`### Constraints`, ``)
      for (const [k, v] of Object.entries(report.problem.constraints)) lines.push(`- **${k}:** ${v}`)
      lines.push(``)
    }
    if (report.problem.existingStack?.length) {
      lines.push(`### Existing Stack`, ``)
      lines.push(...report.problem.existingStack.map(s => `- ${s}`), ``)
    }
    if (report.problem.successMetrics?.length) {
      lines.push(`### Success Metrics`, ``)
      lines.push(...report.problem.successMetrics.map(m => `- ${m}`), ``)
    }

    lines.push(`---`, ``, `## Architecture Candidates`, ``)
    report.candidates.forEach((c, i) => {
      lines.push(
        `### ${i + 1}. ${c.name}`, ``,
        c.description, ``,
        `**Key Components:** ${c.keyComponents.join(', ')}`, ``,
        `**Best For:** ${c.bestFor}`, ``
      )
    })

    for (const section of report.sections) {
      lines.push(`---`, ``, `## ${section.title}`, ``, section.content, ``)
    }

    const slug = report.problem.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')
    const outPath = path.join(outDir, `${slug}-analysis.md`)
    fs.writeFileSync(outPath, lines.join('\n'))
    return outPath
  }
}
